apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: spring-test-cluster
  region: ap-southeast-2
  version: "1.30"
vpc:
  id: "vpc-0702a96dea064ab40"
  subnets:
    private:
      ap-southeast-2a:
        id: "subnet-0f0208e7e196d5a90"
      ap-southeast-2b:
        id: "subnet-0293c6e8237cf40d0"
    public:
      ap-southeast-2a:
        id: "subnet-0d16ce1c8a7742e14"
      ap-southeast-2b:
        id: "subnet-028b9e5241aa4043c"
managedNodeGroups:
  - name: ng-1
    labels: { role: worker }
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: ec2-db-key-pair123
    iam:
      withAddonPolicies:
        imageBuilder: true
        awsLoadBalancerController: true
        autoScaler: true
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        - "arn:aws:iam::652468253696:policy/AWSLoadBalancerControllerIAMPolicy"
