apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spring-test-cluster
  region: ap-south-1
  version: "1.30"

vpc:
  id: "vpc-0d8fd2a1689802dad"
  subnets:
    private:
      ap-south-1a:
        id: "subnet-058c6387214018313"
      ap-south-1b:
        id: "subnet-0913ef7a160140349"
    public:
      ap-south-1a:
        id: "subnet-0ee25220639880092"
      ap-south-1b:
        id: "subnet-0dfbaa9dfae282d68"

managedNodeGroups:
  - name: ng-1
    labels: { role: worker }
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: ec2-db-key-pairtoday
    iam:
      withAddonPolicies:
        imageBuilder: true
        awsLoadBalancerController: true
        autoScaler: true

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        - "arn:aws:iam::322814812989:policy/AWSLoadBalancerControllerIAMPolicy"
