apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: spring-test-cluster
  region: ap-southeast-2
  version: "1.30"
vpc:
  id: "vpc-0c1d4e81c294e4a05"
  subnets:
    private:
      ap-southeast-2a:
        id: "subnet-0bc1cac655537c271"
      ap-southeast-2b:
        id: "subnet-0f9bda511b8a21502"
    public:
      ap-southeast-2a:
        id: "subnet-0c8f99333867e87d0"
      ap-southeast-2b:
        id: "subnet-01856d094104008f8"
managedNodeGroups:
  - name: ng-1
    labels: { role: worker }
    instanceType: c7i-flex.large
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: ec2-db-key-pair123
    iam:
      withAddonPolicies:
        imageBuilder: true
        awsLoadBalancerController: true
        autoScaler: true
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        - "arn:aws:iam::322814812989:policy/AWSLoadBalancerControllerIAMPolicy"
