replicaCount: 1

image:
  repository: 258975980349.dkr.ecr.ap-southeast-2.amazonaws.com/springboot-mysql-eks
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

mysql:
  databaseName: springbootdb

serviceAccount:
  create: false
  annotations: {}
  automount: true
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: spring-eks-alb
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

livenessProbe: {}
readinessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

httpRoute:
  enabled: false
